<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.pikamug.quests</groupId>
        <artifactId>quests-parent</artifactId>
        <version>5.3.3</version>
    </parent>
    <artifactId>quests-fabric</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <!-- ConversationAPI-Fabric -->
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <!--<repository>
            <id>fabricmc</id>
            <url>https://maven.fabricmc.net/</url>
        </repository>-->
    </repositories>

    <dependencies>
        <!--<dependency>
            <groupId>net.fabricmc</groupId>
            <artifactId>fabric-loader</artifactId>
            <version>0.16.10</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.fabricmc.fabric-api</groupId>
            <artifactId>fabric-api</artifactId>
            <version>0.100.0+1.21</version>
            <scope>provided</scope>
        </dependency>-->
        <dependency>
            <groupId>com.github.Browsit</groupId>
            <artifactId>ConversationAPI-Fabric</artifactId>
            <version>-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>me.pikamug.quests</groupId>
            <artifactId>quests-api</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
